Analyzer
moozeq/biopython pull request #7
Opened 2020-05-22 11:33 UTC by KacDom

Added:

1. rounding  result values in SeqAnalyzer class (to 3 decimal places)
2. sequences that are to short (<10 aa) and contain forbidden aa characters are discarded and the class doesn't perform any calculations on them
3. wrote first version of analyzer.test.py that tests all functions of SeqAnalyzer class. Not all parts of script are written in PEP 8 convention - strings with example results of functions are written in one lines so that the script is easier to read

kacdom

2020-05-22 17:39 UTC, moozeq requested changes
Make rounding configurable and reformat comprehensions

2020-05-22 17:39 UTC, moozeq commented on Bio/SeqAnalysis/SeqAnalyzer.py
> +                            }
Try to not use generic names `key`, `value` etc. I think you may want to reformat these lines to something more readable like this:
```
sequences = {seq_id: str(seq_data.seq) for seq_id, seq_data in data.items()}
id_seq_dictionary = {
    seq_id: seq
    for seq_id, seq in sequences.items()
    if not (set('BZXJ').intersection(seq)) and len(seq) >= 10
}
```

2020-05-22 17:39 UTC, moozeq commented on Bio/SeqAnalysis/SeqAnalyzer.py
> +        median_length = round(float(np.median(list_of_lengths)), 3)
Make rounding configurable, i.e. add field in `SeqAnalyzer` class: `self.rounding = 3`

2020-05-22 17:39 UTC, moozeq commented on Bio/SeqAnalysis/SeqAnalyzer.py
> +        pi = [round(seq.isoelectric_point(), 3) for seq in list_of_proteinanalysis_objects]
Same as above, it's more convinient if instead of use `3` you'll use `self.rounding` variable which is configurable in `def __init__`

2020-05-22 17:39 UTC, moozeq commented on Bio/SeqAnalysis/SeqAnalyzer.py
> +                                 ]
Again:

- rounding should be configurable
- complex comprehensions should be done more readable, i.e.

```
flexibility = [aa.flexibility() for aa in list_of_proteinanalysis_objects]
flexibility = [
    round(sum(flex) / len(flex), self.rounding)
    for flex in flexibility
]
```

2020-05-22 17:39 UTC, moozeq commented on Bio/SeqAnalysis/SeqAnalyzer.py
> +            i: round(list_c_terminus.count(i) / len(set(list_c_terminus)), 3) for i in set(list_c_terminus)
Rounding should be configurable

2020-05-22 17:39 UTC, moozeq commented on Bio/SeqAnalysis/SeqAnalyzer.py
> +            i: round(list_n_terminus.count(i) / len(set(list_n_terminus)), 3) for i in set(list_n_terminus)
Rounding should be configurable

2020-05-22 17:39 UTC, moozeq commented on Bio/SeqAnalysis/analyzer_tests.py
> +                        }
Closing `}` should be at the beginning of the line:
```
test_data_dict_of_str = {
(...)
}
```

2020-05-22 17:39 UTC, moozeq commented on Bio/SeqAnalysis/analyzer_tests.py
> +                                                }
Same story as above

2020-05-23 12:42 UTC, KacDom commented
Requested changes have been made and also fixed bug in doctests. Scripts seem to be ready to get pulled.

2020-05-27 20:58 UTC, moozeq approved these changes

2020-05-27 20:59 UTC, merged