Sequences vis
moozeq/biopython pull request #9
Opened 2020-06-02 15:40 UTC by erpeg

Added all types of plots (bar, bar interactive, box and scatter). Documentation finished, everything should work properly.

2020-06-02 23:13 UTC, moozeq requested changes
Parameters in functions without types, errors not handled properly, some naming issues, creating strings with '+', some minor issues with pythonic way of coding

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +    A class, that takes in two dictionaries from SeqAnalysis.SeqAnalyzer and plots selected values (parameters) in
Inside of module you can use just `SeqAnalyzer` name instead of full path which I think should be `SeqAnalysis.SeqAnalyzer.SeqAnalyzer`

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +    def __init__(self, one_big_dict, dict_of_many_small_dicts):
Yees, these names definately should be changed, I suggest:
`one_big_dict ` -> `merged_sequences`
`dict_of_many_small_dicts ` -> `separated_sequences`

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +        self.dict_for_ax_units = {
Instead of using `dict_`/`dict_for_` in every name, you may just use names:
`dict_for_ax_units` -> `ax_units`
`dict_for_title_bar` -> `bar_titles`

But your way is not incorrect, so it's not a problem, just commenting

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +    def __init__(self, one_big_dict, dict_of_many_small_dicts):
No types for input parameters:
`def __init__(self, one_big_dict: Dict[str, Union[list, dict]], dict_of_many_small_dicts: Dict[str, dict]):`

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +    def get_colors(self, for_dict=None) -> Dict:
Same as above, no type for `for_dict` parameter

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +            list_for_colors = for_dict
In pythonic way these 5 lines should be written as single line:
`dict_of_colors = for_dict if for_dict else self.ids`

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +    def matplotlib_legend(self, plt, dict_for_leg, leg_size):
Same as above, no types for input parameters, add them here and you won't need to add them in docstrings

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +        :param leg_size: int; size of legend
As I mentioned above, move types from docstring to function declaration

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +    def ax_and_sup_title_bar_box(self, plt, in_parameter, sup_fontsize, x_fontsize, y_fontsize, mode=None):
Again, function declaration without types

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +            print('Choose proper mode of ax_and_sup_title_bar_box function.')
You should avoid construction like this, in pythonic way:
```
titles = {
    'bar': self.dict_for_title_bar[in_parameter],
    'box': self.dict_for_title_box[in_parameter]
}
if mode not in titles:
    print('Choose proper mode of ax_and_sup_title_bar_box function.')
plt.title(titles.get(mode, '<generic title>'), fontsize=sup_fontsize)
```

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +                                  z_parameter=None):
Again, no types

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +                           z_parameter].lower() + ' as bubble size) of seuqences'
Wrong, do not use merging string like that, it's very dangerous habit, i.e. when creating queries for databases, use [fstring](https://www.python.org/dev/peps/pep-0498/)

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +    def show_or_save_plot(self, save, out_name):
Again, no types

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +    def show_or_save_plot_interactive(self, save, figure, out_name):
Again, no types

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +    def bar_interactive(self, single_seq=None, parameter=None, save=False, size=500, out=None):
Again, no types

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +            y_ax_title_fontsize=14, suptitle_fontsize=13, add_legend=True, leg_size=13, out=None):
Again, no types

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +                add_legend=True, leg_size=13, out=None):
Again, no types

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +        self.ids = self.main_dict['id']
`self.main_dict` tells me nothing

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +            figure.write_html(f'{out_name}.html')
What if I want to save and show? Maybe instead of `save` and `out_name` should be `show` and `out_name`? If `out_name` is presented, then save figure, while `show` may be `True|False`

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +            y_ax_title_fontsize=14, suptitle_fontsize=13, add_legend=True, leg_size=13, out=None):
Again, no types

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +            print('Pass a parameter to plot properly.')
You print message about wrong parameter but do nothing? It'll just crash, do something, set parameter to default value / return error / raise exception (if not handled, should be described in docstring)

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +            fig, ax = plt.subplots(figsize=size)
`if parameter in (self.lists_args + self.dicts_args):`

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +            print('Pass a parameter to plot properly.')
Again, do something if error's detected

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +            print('Pass a parameter to plot properly.')
3rd time

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +
This empty line is unnecessary

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +            print('Pass a parameter to plot properly.')
4th time

2020-06-02 23:13 UTC, moozeq commented on Bio/SeqAnalysis/SeqVisualizer.py
> +                    m_sizes.append(z_parameter)
You are adding `z_parameter` n times?
`m_sizes = [z_parameter] * len(x_data)`

2020-06-03 10:04 UTC, moozeq approved these changes

2020-06-03 10:04 UTC, merged

2020-06-03 10:11 UTC, erpeg commented
Fixed all issues commented by moozeq (changed save and show option, typing in funcitons, removed some of unnecessary loops).